
const SET_TYPE = "SET_TYPE";
const SET_CATEGORY = "SET_CATEGORY";
const SET_PROVINCE = "SET_PROVINCE";
const SET_DISTRICT = "SET_DISTRICT";
const SET_WARD = "SET_WARD";
const SET_STREET = "SET_STREET";
const SET_BUILDING_LINE = "SET_BUILDING";
const SET_AREA = "SET_AREA";
const SET_CONSTRUCTION = "SET_CONSTRUCTION";
const SET_FUNCTION = "SET_FUNCTION";
const SET_FURNITURE = "SET_FURNITURE";
const SET_LEGAL = "SET_LEGAL";
const SET_DESCRIPTION = "SET_DESCRIPTION";
const SET_PRICE = "SET_PRICE";
const SET_OWNERNAME = "SET_OWNERNAME";
export {
    SET_TYPE,
    SET_CATEGORY,
    SET_PROVINCE,
    SET_DISTRICT,
    SET_WARD,
    SET_STREET,
    SET_BUILDING_LINE,
    SET_AREA,
    SET_CONSTRUCTION,
    SET_FUNCTION,
    SET_FURNITURE,
    SET_LEGAL,
    SET_DESCRIPTION,
    SET_PRICE,
    SET_OWNERNAME,
};